site_name: Void Static Site
site_description: Мой кастомный сайт на MkDocs
site_author: Иван Моничев

theme:
  name: null
  custom_dir: template/build

nav:
  - Главная: index.md
  - Задание 2: task-2.md


watch:
  - void-theme
  - docs
