name: Build & Deploy MkDocs site to Pages

on:
  push:
    branches: ["main"]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node.js deps
        run: npm ci
        working-directory: template

      - name: Build frontend with Gulp
        run: npx gulp build
        working-directory: template

      - name: Upload theme artifact
        uses: actions/upload-artifact@v4
        with:
          name: void-theme
          path: template/build

  mkdocs:
    runs-on: ubuntu-latest
    needs: frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Download theme artifact
        uses: actions/download-artifact@v4
        with:
          name: void-theme
          path: template/build

      - name: Install Python deps
        run: pip install -r requirements.txt

      - name: Build MkDocs site
        run: mkdocs build --strict

      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site

  deploy:
    runs-on: ubuntu-latest
    needs: mkdocs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: site
          path: site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
